[workspace]
resolver = "2"

members = ["./backend/bin/*", "./backend/crates/*"]
exclude = ["./vendor/futures-loco-protocol"]

[workspace.package]
version = "0.5.1"
license = "Apache-2.0"
authors = ["KiwiTalk contributors"]
edition = "2021"
repository = "https://github.com/dlwltkd/kiwitalk"
rust-version = "1.88.0"

[workspace.dependencies]
tokio = "1"
tauri = "2.11.5"
tauri-plugin-notification = "2.3.3"
log = "0.4.20"
anyhow = "1.0.82"
serde = { version = "1.0.200", features = ["derive"] }

[workspace.dependencies.headless-talk]
version = "0.6.1"
path = "./backend/crates/headless-talk"

[workspace.dependencies.talk-api-internal]
version = "0.4.1"
path = "./backend/crates/talk-api-internal"

[workspace.dependencies.talk-loco-client]
version = "0.6.1"
path = "./backend/crates/talk-loco-client"

[patch.crates-io]
futures-loco-protocol = { path = "./vendor/futures-loco-protocol" }
